/*
 * File: app/view/HomeCard1.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GreenDot.view.HomeCard1', {
    extend: 'Ext.Panel',
    alias: 'widget.homecard1',

    requires: [
        'Ext.Img'
    ],

    config: {
        itemId: 'homecard1',
        layout: 'vbox',
        items: [
            {
                xtype: 'image',
                height: 571,
                itemId: 'openingscreen',
                src: 'resources/myresources/images/svg/OpeningScreen.svg'
            }
        ]
    }

});