/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GreenDot.view.MainView', {
    extend: 'Ext.tab.Panel',

    requires: [
        'GreenDot.view.HomeCard1',
        'GreenDot.view.HomeCard2',
        'Ext.Panel',
        'Ext.tab.Bar',
        'Ext.TitleBar'
    ],

    config: {
        itemId: 'mainView',
        items: [
            {
                xtype: 'container',
                title: 'Home',
                iconCls: 'home',
                itemId: 'hometab',
                layout: {
                    type: 'card',
                    animation: 'slide'
                },
                items: [
                    {
                        xtype: 'homecard1'
                    },
                    {
                        xtype: 'homecard2'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Help',
                iconCls: 'info',
                html: 'Satyajit, Please send me some content for this "Info" section.',
                itemId: 'helpTab'
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'GreenDot'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});