/*
 * File: app/controller/HomeTabController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GreenDot.controller.HomeTabController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            homeCard1: 'panel#homecard1',
            homeCard2: 'panel#homecard2',
            homeTab: 'container#hometab'
        },

        control: {
            "image#openingscreen": {
                tap: 'onOpeningScreenImageTap'
            },
            "image#chargingscreen": {
                tap: 'onChargingScreenImageTap'
            }
        }
    },

    onOpeningScreenImageTap: function(image, e, eOpts) {
        // Get references
        var homeTab = this.getHomeTab();
        var homeCard2 = this.getHomeCard2();

        // Do Business logic here if any

        // Switch to next screen.

        homeTab.setActiveItem(homeCard2);

    },

    onChargingScreenImageTap: function(image, e, eOpts) {
        // Get references
        var homeTab = this.getHomeTab();
        var homeCard1 = this.getHomeCard1();

        // Do Business logic here if any

        // Switch to next screen.

        homeTab.setActiveItem(homeCard1, {type: 'slide', direction: 'right'});

    }

});